### ISSUE TITLE
I think the repo has a personal twilio instance in it

### ISSUE THREAD

**Issue by Baz-Co** [jlengstorf/twilio-gatsby-video-chat#5]
https://github.com/jlengstorf/twilio-gatsby-video-chat/blob/747311de16e55c9386ed2fef0f6e86c9a94825a1/src/hooks/use-twilio-video.js#L100

not sure if it's an issue, but wanted to let you know!

**Comment by jlengstorf** [comment]
yeah, I leave that in so the demo works — it's cheap enough that I don't stress about it, but I do monitor to make sure usage doesn't spike

thank you!
